### ISSUE TITLE
Deployment using Kubernetes or Helm

### ISSUE THREAD

**Issue by Haebuk** [bruin-data/bruin#371]
Hello,

I am interested in deploying the bruin using Kubernetes or Helm. Could you please provide any examples or guidance on how to achieve this? Any documentation or resources would be greatly appreciated.

Thank you!

**Comment by karakanb** [comment]
hey, glad to hear you are interested in going live with Bruin. I know this is not what you asked, but there's a much easier way if that could be an alternative: you can [run Bruin in GitHub Actions](https://bruin-data.github.io/bruin/cicd/github-action.html) with very little configuration.

For Kubernetes, you can run Bruin as a Kubernetes cronjob, e.g. sth like this:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bruin-pipeline-runner
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: repo
            emptyDir: {}
          - name: ssh-key
            secret:
              secretName: ssh-key
              defaultMode: 0400
          initContainers:
          - name: git-sync
            image: k8s.gcr.io/git-sync/git-sync:v3.6.2
            volumeMounts:
            - name: repo
              mountPath: /repo
            - name: ssh-key
              mountPath: /etc/git-secret
            env:
            - name: GIT_SYNC_REPO
              value: "git@github.com:your-org/your-repo.git"  # Replace with your repo
            - name: GIT_SYNC_BRANCH
              value: "main"  # Replace with your branch
            - name: GIT_SYNC_ROOT
              value: "/repo"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: "/etc/git-secret/ssh-privatekey"
          containers:
          - name: bruin-runner
            image: curlimages/curl:latest
            volumeMounts:
            - name: repo
              mountPath: /repo
            command:
            - /bin/sh
            - -c
            - |
              curl -LsSf https://raw.githubusercontent.com/bruin-data/bruin/refs/heads/main/install.sh | sh
              cd /repo
              ~/.local/bin/bruin run /repo
          restartPolicy: OnFailure
```
I haven't tested this above but on a quick look, it looks good to me.

This CronJob spec should be changed according to a few different questions:
- where does the code live?
- how often do you want to run the pipeline?
- do you have a pre-built image that contains Bruin binary?
    - we'll look into publishing official Docker images for this.
- do you have multiple pipelines?

Based on these you can customize them further.

Let me know if this helps. Feel free to [join our Slack community](https://join.slack.com/t/bruindatacommunity/shared_invite/zt-2dl2i8foy-bVsuMUauHeN9M2laVm3ZVg) to talk more about this as well!
