### ISSUE TITLE
YAML Parsing Error for Asset Definition File

### ISSUE THREAD

**Issue by DjamilaBaroudi** [bruin-data/bruin#95]
## Description:
When attempting to render an asset definition file with a `/` in the `materialization field, the following error occurs:
```bash
Failed to read the asset definition file: error creating task from file 'pipeline-two/assets/test5.sql': yaml: line 5: could not find expected ':'
```

## Steps to Reproduce:

1. Create an asset definition with the following structure:

```yaml
/* @bruin
name: test
description: This is a description
type: bq.sql
materialization:/
   type: table
@bruin */

select 1 as one
```

2. Run the command:
```bash
bruin render -o json path-to-the-file/test.sql
```
## Expected Behavior:
The error should be returned in a JSON format, as the `-o json` flag is included, instead of showing a text error.

## Example of Correct Format: 
The rendering error when there is a formatting problem should be returned as a JSON when the `-o json` flags are added:

Example of a formatting error:
```yaml
name: test
description: This is a description
type: bq.sql
materialization:
  type: tables
  ```
  
Running the command: 
  ```bash
bruin render -o json path-to-the-file/test.sql
```
Returns: 

  ```bash
  {
  "error": "Failed to materialize the query: unsupported materialization type - strategy combination: (`tables` - ``)\n"
}
```
